const mongoose = require('mongoose');

var companyMasterSchema = new mongoose.Schema({
    _id:mongoose.Schema.Types.ObjectId,
    companyCode:{
        type:String,
        required:true
    },
    doj:{
        type:Date,
        required:true
    },
    businessCategoryId:{
        type:mongoose.Types.ObjectId,
        ref:'categoryMaster'
    },
    companyName:{
        type:String,
        required:true
    },
    addressLine1:{
        type:String,
        required:true
    },
    addressLine2:{
        type:String
    },
    cityMasterId:{
        type:mongoose.Types.ObjectId,
        ref:'cityMaster'
    },
    zipcode:{
        type:String
    },
    mapLocation:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true
    },
    fax:{
        type:String
    },
    url:{
        type:String,
        required:true
    },
    supportEmail:{
        type:String,
        required:true
    },
    adminEmail:{
        type:String,
        required:true
    },
    adminMobile:{
        type:String,
        required:true
    },
    adminPassword:{
        type:String,
        required:true
    },
    gstinNo:{
        type:String
    },
    paNo:{
        type:String
    },
    bank:{
        bankName:{
            type:String,
            required:true
        },
        bankBranchName:{
            type:String,
            required:true
        },
        bankAddress:{
            type:String,
            required:true
        },
        bankCity:{
            type:String,
            required:true
        },
        bankState:{
            type:String,
            required:true
        },
        bankAccountNo:{
            type:String,
            required:true
        },
        bankIfscCode:{
            type:String,
            required:true
        }
    },
    companyType:{
        type:String,
        required:true
    },
    personName:{
        type:String,
        required:true
    },
    personPhoto:{
        type:String,
        required:true
    },
    aadharCard:{
        type:String,
        required:true
    },
    panCard:{
        type:String,
        required:true
    },
    cancelledCheque:{
        type:String,
        required:true
    },
    weekStartDay:{
        type:String,
        required:true
    },
    companyLogo:{
        type:String,
        required:true
    },
    cancellationPolicy:{
        type:String
    },
    companyHtmlPage:{
        type:String,
        required:true
    },
    registrationValidUpto:{
        type:Date,
        required:true
    },
    active:{
        type:Boolean,
        default:true
    }


});

module.exports = mongoose.model('companyMaster',companyMasterSchema);