const mongoose = require('mongoose');

var registrationFeesSchema = new mongoose.Schema({
    _id:mongoose.Schema.Types.ObjectId,
    companyId:{
        type:mongoose.Types.ObjectId,
        ref:'companyMaster'
    },
    regDate:{
        type:Date,
        required:true
    },
    membershipTypeID:{
        type:mongoose.Types.ObjectId,
        ref:'membershipTypeMst'
    },
    amtPaid:{
        type:Number,
        required:true
    },
    taxableValue:{
        type:Number,
        required:true
    },
    cGSTAmt:{
        type:Number,
        required:true
    },
    sGSTAmt:{
        type:Number,
        required:true
    },
    iGSTAmt:{
        type:Number,
        required:true
    },
    payModeID:{
        type:Number,
        required:true
    },
    payThrough:{
        type:String,
        required:true
    },
    cardNumber:{
        type:String,
        required:true
    },
    cVCCode:{
        type:String,
        required:true
    },
    expiryDate:{
        type:Date,
        required:true
    },
    nameOnCard:{
        type:String,
        required:true
    },
    payStatus:{
        type:String,
        required:true
    },
    payStatusDecription:{
        type:String,
        required:true
    },
    payDateTime:{
        type:Date,
        required:true
    },
    transactionNo:{
        type:String,
        required:true
    },
    billNo:{
        type:String,
        required:true
    },
    billEmailed:{
        type:Boolean
    },
    EmailDateTime:{
        type:Date,
        required:true
    }
});

module.exports = mongoose.model('registrationFees',registrationFeesSchema);